url: https://pirateandthequeen.github.io
baseurl: /wedding/

# Site settings
title: The Pirate and the Queen get married!
email: piratepeel+nicolettathequeen@gmail.com
description: "The Pirate and the Queen are getting married! Find out all the details here."


# Team names, titles and social links
#people:
#- name: Diana Petersen
#  pic: 3
#  position: Lead Developer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty
